---
# tasks file for mywebapp
- name: vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: update
  apt:
          update_cache: true
          cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: install
  package:
          name: "{{ web }}" 
          state: present
- name: web content
  copy:
          dest: /var/www/html/index.html
          content: This is the web content
- name: service
  service:
          name: "{{ web }}"
          state: started
          enabled: true
